"""Domain skills: the Claude Code adapter of the stage contracts, installed into a data root.

Claude Code loads skills from the project it is opened in, so a data root needs its own
copies. The sources live in the package; `install` copies them with a generated-file
notice after the frontmatter, and a test keeps the copies in the framework repository
identical to what `install` produces.
"""

from __future__ import annotations

from pathlib import Path

from . import __version__
from .dataroot import package_dir
from .errors import CvacError

NOTICE = (
    "<!-- generated by `cvac skills install` from cv-as-code {version}; "
    "edit the source in the framework repository, not this copy -->"
)


def skills_dir() -> Path:
    return package_dir() / "skills"


def list_skills() -> list[str]:
    return sorted(p.name for p in skills_dir().iterdir() if (p / "SKILL.md").is_file())


def rendered(name: str) -> str:
    """The SKILL.md as installed: the source with the notice right after the frontmatter."""
    source = (skills_dir() / name / "SKILL.md").read_text("utf-8")
    if not source.startswith("---\n"):
        raise CvacError(f"skill `{name}` has no frontmatter")
    end = source.index("\n---\n", 4) + len("\n---\n")
    return source[:end] + NOTICE.format(version=__version__) + "\n" + source[end:]


def install(target: Path) -> list[Path]:
    """Write every domain skill under target/<name>/SKILL.md; returns the files written."""
    written: list[Path] = []
    for name in list_skills():
        path = target / name / "SKILL.md"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(rendered(name), "utf-8")
        written.append(path)
    return written
